edition = "2024"
style_edition = "2024"
required_version = "1.8.0"
unstable_features = true
ignore = []

# # array_width = 60
# # attr_fn_like_width = 70
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
chain_width = 30 # circle back to this
color = "Auto"
combine_control_expr = false
comment_width = 100
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
# # emit_mode = "Files"
empty_item_single_line = false
enum_discrim_align_threshold = 80
error_on_line_overflow = false
error_on_unformatted = false
fn_call_width = 60
fn_params_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
format_generated_files = true
format_macro_matchers = true
format_macro_bodies = true
skip_macro_invocations = []
format_strings = false
hard_tabs = false
hex_literal_case = "Upper"
show_parse_errors = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
merge_derives = true
imports_granularity = "Crate"
newline_style = "Auto"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
short_array_element_width_threshold = 5
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
struct_lit_width = 18
struct_variant_width = 35
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
where_single_line = false
wrap_comments = true
make_backup = false
max_width = 100
